# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [2]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

height_np = np.array(height)
weight_np = np.array(weight)

answer = (weight_np/(height_np**2)) * 730

print(answer)


[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [28]:
# Example makeMatrix(param1,param2) -- Extra params can be added here as well

# This is INCLUSIVE of the high
# shape must be passed in as a tuple of two digits, and must be possible based on the 
# size of the range passed in. Also, the data_type can only be float or int
def makeMatrix(low,high,shape,data_type = float):
    if data_type == int:
        size = np.multiply(shape[0],shape[1])
        arr = np.random.randint(low,(high+1),size)
        matrix = arr.reshape(shape)
    else:
        matrix = np.random.uniform(low, high, shape)
    print(f"Here is a matrix of numbers between {low} and {high} of shape {shape}:")
    print(f"{matrix}")

makeMatrix(0,7,(2,4),int)
makeMatrix(1,16,(4,4),float)

Here is a matrix of numbers between 0 and 7 of shape (2, 4):
[[4 3 7 6]
 [3 1 1 1]]
Here is a matrix of numbers between 1 and 16 of shape (4, 4):
[[ 3.45953341 10.10785665  2.24409472 12.36380494]
 [10.32361687  2.54659484 13.83913266  8.05651644]
 [12.6348418  10.08980567 11.50925841  9.20282312]
 [ 2.67652039 15.10093368 11.89844885  6.87276223]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [41]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d=','):
    data = np.genfromtxt(filename,delimiter = d,skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS,dtype = DATATYPES)
    return data

sox2017 = load_data('../files/redsox_2017_hitting.txt')
sox2018 = load_data('../files/redsox_2018_hitting.txt')

def betterYear():
    slg1 = np.average(sox2017['SLG'])
    slg2 = np.average(sox2018['SLG'])
    if slg1 > slg2:
        print(f"2017 had a higher average slugging percentage of {slg1}, for a difference of {slg1-slg2}")
    elif slg2 > slg1:
        print(f"2018 had a higher average slugging percentage of {slg2}, for a difference of {slg2-slg1}")
    else:
        print(f"Somehow, the averages are exactly the same...")

betterYear()

        

2017 had a higher average slugging percentage of 0.393347829580307, for a difference of 0.005847841501235962
